### ISSUE TITLE
Question: Porting to Spark/Particle core

### ISSUE THREAD

**Issue by JamiePhonic** [HobbyComponents/HCuOLED#1]
Would it be at all possible for this library to be ported for use with the Spark/Particle core development platform?
Thus far, i have only found 1 usable library for the core that works with the SH1106 driver, but its nowhere near as functional, user friendly or configurable as this one.
For now im driving the HCMODU0058 1.3" Oled with the arduino and just passing the data to it over serial which is working, but not very stable.
If its not possible, then i may have to return the HCMODU0058 modules and get different ones that use the SSD1306 driver chip instead since adafruit has compatable librarys available for those.

**Comment by HobbyComponents** [comment]
Hi,

Thanks for your enquiry. I'm not sure if you are asking if it is  
technically possible to port the library, or if you asking if we can port  
it over to the platform ourselves. If it is the former, although we are  
not familiar with that development board the library is written in C++ and  
makes use of the hardware SPI interface so technically it should be  
possible for it to be ported to any platform that either has or can  
emulate an SPI interface and has a C compiler. However as we don't  
currently stock the Spark/Particle core development platform I'm afraid we  
don't have any plans to port the library over to it ourselves. Of course  
should we stock this development board at any point in the future we may  
consider porting it.

Regards

Andrew

On Fri, 09 Oct 2015 13:00:08 +0100, James notifications@github.com wrote:

> Would it be at all possible for this library to be ported for use with  
> the Spark/Particle core development platform?
> Thus far, i have only found 1 usable library for the core that works  
> with the SH1106 driver, but its nowhere near as functional, user  
> friendly or >configurable as this one.
> For now im driving the HCMODU0058 1.3" Oled with the arduino and just  
> passing the data to it over serial which is working, but not very stable.
> If its not possible, then i may have to return the HCMODU0058 modules  
> and get different ones that use the SSD1306 driver chip instead since  
> adafruit >has compatable librarys available for those.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Hobby Components Ltd (www.hobbycomponents.com)

**Comment by HobbyComponents** [comment]
As significant time as passed I'm closing this issue.
