### ISSUE TITLE
Very slow implementation of Erase()

### ISSUE THREAD

**Issue by vladyslav-savchenko** [HobbyComponents/HCuOLED#3]
The implementation of Erase() is very inefficient. The patch please find attached.

[patch.txt](https://github.com/HobbyComponents/HCuOLED/files/138716/patch.txt)

**Comment by HobbyComponents** [comment]
Thanks for the patch. I've now added it to v0.2 of this library.

**Comment by vladyslav-savchenko** [comment]
I do not remember the details and can not give you an example (it was 10 months ago! just believe me), but:
    the implementation of Line(), called from Rect() was much slower in comparison with direct called Plot()

**Comment by HobbyComponents** [comment]
Hi,

Thanks for the reply. I think there is some misunderstanding. I've implemented your quicker erase function in the new version of the library uploaded this morning. The comment was about the other issue you opened relating to the last point for lines and rectangles. Unfortunately I cannot replicate this issue. If you're not able to give an example at the moment I can just close the issue and it can then just be reopened should you come across it again in the future.
